import PptxGenJS from 'pptxgenjs';
import type { AllWorkshopArtifacts } from '@/lib/build-pack/load-workshop-artifacts';
import type { PresentationSummary } from '@/lib/ai/prompts/presentation-generation';

// ── Design tokens ──────────────────────────────────────────────────────
const C = {
  navy: '1B2A4A',
  darkNavy: '0F1B33',
  white: 'FFFFFF',
  lightGray: 'F5F6FA',
  mediumGray: 'E2E4EB',
  textGray: '6B7280',
  accent: '3B82F6',
  green: '10B981',
  red: 'EF4444',
  amber: 'F59E0B',
};

const F = { title: 'Calibri', body: 'Calibri' };

let slideNum = 0;
const dateStr = () => new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

/** Step key → display title */
const STEP_TITLES: Record<string, string> = {
  challenge: 'Challenge Definition',
  stakeholderMapping: 'Stakeholder Map',
  userResearch: 'User Research',
  senseMaking: 'Research Sense Making',
  persona: 'Persona Development',
  journeyMapping: 'Customer Journey Map',
  reframe: 'Reframed Challenge',
  ideation: 'Ideation',
  concept: 'Concept Development',
  validate: 'Validation & Synthesis',
};

/** Step ordering */
const STEP_ORDER = [
  'challenge',
  'stakeholderMapping',
  'userResearch',
  'senseMaking',
  'persona',
  'journeyMapping',
  'reframe',
  'ideation',
  'concept',
  'validate',
];

/**
 * Build a PPTX buffer from captured canvas images + text summaries.
 * Each step is an image slide with a brief summary overlay.
 */
export async function buildPresentation(
  stepImages: Record<string, string>,
  summaries: Record<string, string>,
  conceptName: string,
  summary: PresentationSummary,
): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.author = 'WorkshopPilot.ai';
  pptx.company = 'WorkshopPilot.ai';
  pptx.subject = `${conceptName} — Stakeholder Presentation`;
  pptx.title = `${conceptName} — Stakeholder Presentation`;
  pptx.layout = 'LAYOUT_16x9';

  slideNum = 0;

  // 1. Title slide
  addTitleSlide(pptx, conceptName, summary.subtitle);

  // 2. Executive summary
  addExecSummarySlide(pptx, summary.executiveSummary, summaries);

  // 3-N. Step slides — image-based, only for steps with captured images
  for (const stepKey of STEP_ORDER) {
    const imageData = stepImages[stepKey];
    if (!imageData) continue;

    const title = STEP_TITLES[stepKey] || stepKey;
    const stepSummary = summaries[stepKey] || '';
    addImageSlide(pptx, title, imageData, stepSummary);
  }

  // Thank you
  addThankYouSlide(pptx, conceptName);

  const output = await pptx.write({ outputType: 'nodebuffer' });
  return output as Buffer;
}

/**
 * Legacy build function for backward compatibility.
 * Accepts AllWorkshopArtifacts + PresentationSummary (the old signature).
 * Falls back to text-only slides when no images are provided.
 */
export async function buildPresentationLegacy(
  artifacts: AllWorkshopArtifacts,
  summary: PresentationSummary,
): Promise<Buffer> {
  const concept = artifacts.concept as Record<string, unknown> | null;
  const concepts = (concept?.concepts as Array<Record<string, unknown>>) || [];
  const primaryConcept = concepts[0] || concept || {};
  const conceptName = (primaryConcept.name as string) || (primaryConcept.conceptName as string) || (concept?.name as string) || 'Product';

  // Generate text summaries from artifacts
  const summaries = generateSummariesFromArtifacts(artifacts);

  // No images — build with just summaries (text-only fallback)
  return buildPresentation({}, summaries, conceptName, summary);
}

// ── Helpers ────────────────────────────────────────────────────────────
function footer(slide: PptxGenJS.Slide) {
  slideNum++;
  slide.addText(`Generated by WorkshopPilot.ai  |  ${dateStr()}`, { x: 0.5, y: 5.15, w: 7, fontSize: 7, color: C.textGray, fontFace: F.body });
  slide.addText(`${slideNum}`, { x: 8.5, y: 5.15, w: 1, fontSize: 7, color: C.textGray, fontFace: F.body, align: 'right' });
}

// ── Title ──────────────────────────────────────────────────────────────
function addTitleSlide(pptx: PptxGenJS, name: string, subtitle: string) {
  const slide = pptx.addSlide();
  slide.background = { color: C.navy };
  slide.addText(name, { x: 1, y: 1.4, w: 8, fontSize: 36, fontFace: F.title, color: C.white, bold: true });
  slide.addShape(pptx.ShapeType.rect, { x: 1, y: 2.3, w: 2, h: 0.04, fill: { color: C.accent } });
  slide.addText(subtitle, { x: 1, y: 2.55, w: 8, fontSize: 16, fontFace: F.body, color: C.mediumGray });
  slide.addText(dateStr(), { x: 1, y: 3.6, w: 8, fontSize: 13, fontFace: F.body, color: C.textGray });
}

// ── Executive Summary ──────────────────────────────────────────────────
function addExecSummarySlide(pptx: PptxGenJS, summaryText: string, summaries: Record<string, string>) {
  const slide = pptx.addSlide();
  slide.background = { color: C.white };
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 10, h: 1.1, fill: { color: C.navy } });
  slide.addText('Executive Summary', { x: 0.5, y: 0.15, w: 9, fontSize: 22, fontFace: F.title, color: C.white, bold: true });

  slide.addText(summaryText, { x: 0.7, y: 1.4, w: 8.6, fontSize: 14, fontFace: F.body, color: C.darkNavy, lineSpacingMultiple: 1.4 });

  // Key facts from summaries
  const facts: Array<{ label: string; value: string }> = [];
  if (summaries.challenge) facts.push({ label: 'Challenge', value: summaries.challenge.slice(0, 80) });
  if (summaries.persona) facts.push({ label: 'Persona', value: summaries.persona.slice(0, 80) });
  if (summaries.concept) facts.push({ label: 'Solution', value: summaries.concept.slice(0, 80) });

  if (facts.length > 0) {
    const factY = 3.2;
    const factW = 8.6 / facts.length;
    facts.forEach((f, i) => {
      const fx = 0.7 + i * factW;
      slide.addShape(pptx.ShapeType.rect, { x: fx, y: factY, w: factW - 0.15, h: 1.2, fill: { color: C.lightGray }, rectRadius: 0.08 });
      slide.addText(f.label, { x: fx + 0.15, y: factY + 0.1, w: factW - 0.4, fontSize: 9, fontFace: F.title, color: C.accent, bold: true });
      slide.addText(f.value, { x: fx + 0.15, y: factY + 0.4, w: factW - 0.4, fontSize: 10, fontFace: F.body, color: C.darkNavy });
    });
  }

  footer(slide);
}

// ── Image-based step slide ─────────────────────────────────────────────
function addImageSlide(pptx: PptxGenJS, title: string, imageData: string, stepSummary: string) {
  const slide = pptx.addSlide();
  slide.background = { color: C.white };

  // Full-bleed image (10" x 5.625" = 16:9)
  slide.addImage({
    data: imageData,
    x: 0,
    y: 0,
    w: 10,
    h: 5.625,
  });

  // Semi-transparent summary bar at bottom (if summary exists)
  if (stepSummary) {
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 4.6,
      w: 10,
      h: 1.03,
      fill: { color: C.navy, transparency: 15 },
    });
    slide.addText(title, {
      x: 0.3,
      y: 4.65,
      w: 9.4,
      fontSize: 11,
      fontFace: F.title,
      color: C.white,
      bold: true,
    });
    slide.addText(stepSummary, {
      x: 0.3,
      y: 4.95,
      w: 9.4,
      fontSize: 8,
      fontFace: F.body,
      color: C.mediumGray,
    });
  }
}

// ── Thank You ──────────────────────────────────────────────────────────
function addThankYouSlide(pptx: PptxGenJS, conceptName: string) {
  const slide = pptx.addSlide();
  slide.background = { color: C.navy };
  slide.addText('Thank You', { x: 1, y: 1.6, w: 8, fontSize: 36, fontFace: F.title, color: C.white, bold: true, align: 'center' });
  slide.addText(conceptName, { x: 1, y: 2.5, w: 8, fontSize: 18, fontFace: F.body, color: C.mediumGray, align: 'center' });
  slide.addText('Generated by WorkshopPilot.ai', { x: 1, y: 3.8, w: 8, fontSize: 11, fontFace: F.body, color: C.textGray, align: 'center' });
}

// ── Summary generation from artifacts (for exec summary facts) ─────────
export function generateSummariesFromArtifacts(artifacts: AllWorkshopArtifacts): Record<string, string> {
  const summaries: Record<string, string> = {};

  // Challenge
  if (artifacts.challenge) {
    const c = artifacts.challenge as Record<string, unknown>;
    summaries.challenge = (c.problemStatement as string) || (c.hmwStatement as string) || '';
  }

  // Stakeholder Mapping
  if (artifacts.stakeholderMapping) {
    const s = artifacts.stakeholderMapping as Record<string, unknown>;
    const stakeholders = (s.stakeholders as Array<{ name: string }>) || [];
    summaries.stakeholderMapping = `${stakeholders.length} stakeholders identified across core, direct, and indirect rings`;
  }

  // User Research
  if (artifacts.userResearch) {
    const u = artifacts.userResearch as Record<string, unknown>;
    const insights = (u.insights as Array<{ finding: string }>) || [];
    summaries.userResearch = insights.length > 0
      ? `${insights.length} key insights from user research`
      : '';
  }

  // Sense Making
  if (artifacts.senseMaking) {
    const sm = artifacts.senseMaking as Record<string, unknown>;
    const themes = (sm.themes as Array<{ name: string }>) || [];
    summaries.senseMaking = themes.length > 0
      ? `Key themes: ${themes.slice(0, 3).map(t => t.name).join(', ')}`
      : '';
  }

  // Persona
  if (artifacts.persona) {
    const p = artifacts.persona as Record<string, unknown>;
    const name = (p.name as string) || '';
    const role = (p.role as string) || '';
    summaries.persona = [name, role].filter(Boolean).join(' — ');
  }

  // Journey Mapping
  if (artifacts.journeyMapping) {
    const j = artifacts.journeyMapping as Record<string, unknown>;
    const stages = (j.stages as Array<Record<string, unknown>>) || [];
    const dipStage = stages.find(s => s.isDip);
    summaries.journeyMapping = dipStage
      ? `${stages.length} stages mapped — key pain point at "${dipStage.name}"`
      : `${stages.length} journey stages mapped`;
  }

  // Reframe
  if (artifacts.reframe) {
    const r = artifacts.reframe as Record<string, unknown>;
    const hmwStatements = (r.hmwStatements as Array<{ fullStatement?: string }>) || [];
    summaries.reframe = hmwStatements[0]?.fullStatement?.slice(0, 120) || '';
  }

  // Ideation
  if (artifacts.ideation) {
    const id = artifacts.ideation as Record<string, unknown>;
    const clusters = (id.clusters as Array<{ theme: string; ideas: unknown[] }>) || [];
    const totalIdeas = clusters.reduce((sum, c) => sum + (c.ideas?.length || 0), 0);
    summaries.ideation = `${totalIdeas} ideas across ${clusters.length} themes`;
  }

  // Concept
  if (artifacts.concept) {
    const c = artifacts.concept as Record<string, unknown>;
    const concepts = (c.concepts as Array<Record<string, unknown>>) || [];
    const primary = concepts[0] || c;
    const name = (primary.name as string) || (primary.conceptName as string) || '';
    const pitch = (primary.elevatorPitch as string) || '';
    summaries.concept = pitch ? `${name}: ${pitch.slice(0, 100)}` : name;
  }

  // Validate
  if (artifacts.validate) {
    const v = artifacts.validate as Record<string, unknown>;
    const confidence = v.confidenceAssessment as Record<string, unknown> | undefined;
    if (confidence?.score) {
      summaries.validate = `Confidence score: ${confidence.score}/10`;
    }
  }

  return summaries;
}
