import type { WorkshopArtifacts } from '@/lib/build-pack/load-workshop-artifacts';

/**
 * Build the Gemini system prompt that instructs it to synthesize workshop artifacts
 * into a V0-optimized prototype prompt.
 */
export function buildPrdGenerationPrompt(artifacts: WorkshopArtifacts): string {
  const artifactJson = JSON.stringify(artifacts, null, 2);

  return `You are a senior product designer. Your job is to transform design thinking workshop outputs into a clear, actionable prompt that V0 (Vercel's AI code generator) can use to build a clickable frontend prototype.

Below are the structured outputs from the workshop. Some sections may be null (the user skipped that step) — omit those sections from your output.

<workshop_artifacts>
${artifactJson}
</workshop_artifacts>

Write a prompt in markdown following this EXACT structure. Keep it under 1500 words. Use natural language, not JSON. Be specific and actionable.

---

Build a frontend prototype for "{concept name from artifacts}".

## What This Product Does
{Write 2-3 sentences combining the elevator pitch and problem statement}

## The User
{Persona name} is a {role} who {bio summary}.
- Goals: {top 3 goals as bullet points}
- Frustrations: {top 3 pains as bullet points}
- Key quote: "{persona quote}"

## The Core Problem
{Combine pain points from sense-making + HMW statement from reframe. If those steps are missing, derive from challenge + persona pains}

## The Solution
{USP from concept} — {billboard headline + subheadline if available}

## Key Features to Prototype
{Derive 3-5 features from the concept, each tied to a specific persona pain point. Format as bullet points with feature name + brief description}

## Pages to Build
{Derive 2-4 pages from the journey stages. Each page should have a clear purpose and list of key UI elements}

## Design Direction
Clean, modern, professional. Focus on the happy path.
Use realistic mock data that reflects the persona's world.

---

IMPORTANT:
- Write the prompt as if speaking directly to V0
- Be specific about UI elements, data to display, and interactions
- Do NOT include any preamble, explanation, or meta-commentary — output ONLY the prompt markdown
- If a section's source data is null/missing, omit that section entirely (except "What This Product Does" and "The Solution" which are always required)`;
}

/**
 * Build the V0 system prompt (static constraints template).
 * This is sent as the system prompt to V0's API, not generated by AI.
 */
export function buildV0SystemPrompt(conceptName: string, personaName: string): string {
  return `You are building a clickable frontend prototype to validate a product concept called "${conceptName}" designed for a user like ${personaName}.

CONSTRAINTS:
- Next.js App Router + React + Tailwind CSS + shadcn/ui
- Frontend ONLY — no database, no auth, no API routes, no backend
- All data is hardcoded mock data in a /lib/mock-data.ts file
- Mock data should feel realistic for the target persona
- Use React useState for interactive behavior (filters, toggles, forms)
- Mobile responsive, polished visual design

WHAT TO BUILD:
- Multiple pages demonstrating the core user flow
- Focus on the happy path — no error handling needed
- Make it feel like a real product a stakeholder could click through

WHAT NOT TO BUILD:
- No login/signup/auth screens
- No real API calls or data fetching
- No complex state management
- No backend routes or server actions
- No payment processing, email, or third-party integrations

DESIGN:
- Use shadcn/ui components (Card, Button, Input, Badge, Tabs, etc.)
- Professional color scheme with clear visual hierarchy
- Hover states and basic transitions for interactivity
- Placeholder images where needed`;
}
