/**
 * Journey Flow Types
 *
 * Dependency-free at runtime — type-only imports keep this safe to import
 * from both server and client code.
 * These are the contracts every other Phase 63/64 file imports.
 */

import type { StrategicIntent } from '@/lib/journey-mapper/types';

// ---------------------------------------------------------------------------
// Phase 64: Flow archetypes + test scope
// ---------------------------------------------------------------------------

/**
 * The structural shape of a generated baseline flow.
 * This is the Phase 64 canonical concept — StrategicIntent is derived from it
 * for Phase 66 prompt-template dispatch via ARCHETYPE_TO_INTENT.
 */
export type FlowArchetype =
  | 'linear-sequence'
  | 'hub-and-spoke'
  | 'single-page-sections'
  | 'funnel'
  | 'branching'
  | 'single-screen-tool'
  | 'loop';

/**
 * Whether the user is testing the end-to-end product journey or a single
 * feature/concept from the workshop.
 */
export type TestScope = 'journey' | 'feature';

/**
 * Single reconciled mapping: archetype (structural pattern) → strategicIntent
 * (product category for Phase 66 prompt-template dispatch).
 *
 * Do NOT maintain a parallel mapping elsewhere. This is the one source of truth.
 * admin-portal has no dedicated archetype — reachable only via LLM output or
 * when intent-detection scores admin-portal highest under hub-and-spoke.
 */
export const ARCHETYPE_TO_INTENT: Record<FlowArchetype, StrategicIntent> = {
  'linear-sequence': 'web-app',
  'hub-and-spoke': 'dashboard',
  'single-page-sections': 'marketing-site',
  'funnel': 'marketing-site',
  'branching': 'web-app',
  'single-screen-tool': 'tool',
  'loop': 'web-app',
};

/** Human-readable display labels for each flow archetype. */
export const ARCHETYPE_LABELS: Record<FlowArchetype, string> = {
  'linear-sequence': 'Linear sequence',
  'hub-and-spoke': 'Hub & spoke',
  'single-page-sections': 'Single-page sections',
  'funnel': 'Funnel',
  'branching': 'Branching flow',
  'single-screen-tool': 'Single-screen tool',
  'loop': 'Engagement loop',
};

export type JourneyFlowUiType =
  | 'dashboard'
  | 'landing-page'
  | 'form'
  | 'table'
  | 'detail-view'
  | 'wizard'
  | 'modal'
  | 'settings'
  | 'auth'
  | 'onboarding'
  | 'search'
  | 'error';

export type JourneyFlowPriority = 'must-have' | 'should-have' | 'nice-to-have';

export interface JourneyFlowNode {
  id: string;                       // 'jf-node-{uuid}'
  name: string;
  uiType: JourneyFlowUiType;
  purpose: string;                  // the "short description" shown on the card
  keyElements: string[];
  addressesPain?: string;
  priority: JourneyFlowPriority;
  position: { x: number; y: number };
  /**
   * Marks a two-sided product explanation node generated by the AI.
   * Annotation nodes are rendered differently on the canvas (amber banner, info icon,
   * non-editable). Phase 66 prompt-building excludes them from the screen list.
   */
  isAnnotation?: boolean;
}

export interface JourneyFlowEdge {
  id: string;                       // 'jf-edge-{uuid}'
  sourceNodeId: string;
  targetNodeId: string;
  sourceHandle?: string;
  targetHandle?: string;
}

export interface JourneyFlowState {
  nodes: JourneyFlowNode[];
  edges: JourneyFlowEdge[];
  isApproved: boolean;
  isDirty: boolean;
  lastSavedAt?: string;
  _schemaVersion: number;           // 1
  // ---------------------------------------------------------------------------
  // Phase 64: generation metadata (all optional — old saved states load cleanly)
  // ---------------------------------------------------------------------------
  /** AI-determined structural pattern. Phase 66 derives strategicIntent via ARCHETYPE_TO_INTENT. */
  flowArchetype?: FlowArchetype;
  /** Product category for Phase 66 prompt-template dispatch; stored alongside archetype. */
  strategicIntent?: StrategicIntent;
  /** Whether the user is testing the whole journey or a single feature/concept. */
  testScope?: TestScope;
  /** Concept name (stable ID) — only when testScope='feature'. */
  selectedConceptId?: string;
  /** ISO timestamp of the last AI generation; used to detect user edits for regenerate confirmation. */
  lastGeneratedAt?: string;
  /** Whether the AI detected a two-sided product; drives annotation node rendering. */
  isTwoSided?: boolean;
}

// ---------------------------------------------------------------------------
// Display label maps
// ---------------------------------------------------------------------------

export const UI_TYPE_LABELS: Record<JourneyFlowUiType, string> = {
  dashboard: 'Dashboard',
  'landing-page': 'Landing Page',
  form: 'Form',
  table: 'Table',
  'detail-view': 'Detail View',
  wizard: 'Wizard',
  modal: 'Modal',
  settings: 'Settings',
  auth: 'Auth',
  onboarding: 'Onboarding',
  search: 'Search',
  error: 'Error Page',
};

export const PRIORITY_LABELS: Record<JourneyFlowPriority, string> = {
  'must-have': 'Must Have',
  'should-have': 'Should Have',
  'nice-to-have': 'Nice to Have',
};

// ---------------------------------------------------------------------------
// Default state
// ---------------------------------------------------------------------------

export const DEFAULT_JOURNEY_FLOW_STATE: JourneyFlowState = {
  nodes: [],
  edges: [],
  isApproved: false,
  isDirty: false,
  _schemaVersion: 1,
};
